members:
  - name: "Universidade Aberta"
    url: "https://portal.uab.pt/"
    image: "partners/aberta.png"
  - name: "Bifröst University"
    url: "https://www.bifrost.is/english/"
    image: "partners/bifrost.png"
  - name: "Universitat Oberta de Catalunya (UOC)"
    url: "https://www.uoc.edu/portal/en/index.html"
    image: "partners/uoc.png"
  - name: "Open University of Cyprus"
    url: "https://www.ouc.ac.cy/index.php/el/"
    image: "partners/ouc.jpg"
  - name: "Daugavpils University"
    url: "https://du.lv/"
    image: "partners/daugavpils.png"
  - name: "FernUniversität Hagen"
    url: "https://www.fernuni-hagen.de/english/"
    image: "partners/feu.png"
  - name: "Hellenic Open University"
    url: "https://www.eap.gr/"
    image: "partners/eap.png"
  - name: "Open Universiteit (OUNL)"
    url: "https://www.ou.nl/"
    image: "partners/ou.png"
  - name: "UNED"
    url: "https://www.uned.es/"
    image: "partners/uned.png"
  - name: "Veliko Tarnovo"
    url: "https://www.uni-vt.bg/eng/"
    image: "partners/vtu.png"

associated_partners:
  - name: "European Association of Distance Teaching Universities"
    url: "https://eadtu.eu/"
    image: "partners/eadtu.jpg"
  - name: "International Association of Universities"
    url: "https://www.iau-aiu.net/"
    image: "partners/iau.png"
  - name: "The Open University"
    url: "https://www.open.ac.uk/"
    image: "partners/tou.png"
  - name: "UNIKO"
    url: "https://unkorce.edu.al/"
    image: "partners/fan.png"
  - name: "Ukrainian Engineering Pedagogic Academy (UEPA)"
    url: "http://uipa.edu.ua/"
    image: "partners/uepa.png"
  - name: "MIT"
    url: "https://www.mit.edu.mk/"
    image: "partners/mit.png"
  - name: "Fédération Interuniversitaire de l’Enseignement à Distance"
    url: "https://www.fied.fr/"
    image: "partners/fied.png"
  - name: "UNIMED"
    url: "https://www.uni-med.net/"
    image: "partners/unimed.jpg"
  - name: "Eurocities"
    url: "https://eurocities.eu/"
    image: "partners/eurocities.jpg"
  - name: "European Leader Association For Rural Development"
    url: "http://elard.eu/"
    image: "partners/elard.jpg"
  - name: "Stifterverband"
    url: "https://www.stifterverband.org/english"
    image: "partners/stifterverband.png"
  - name: "Brightlands"
    url: "https://www.brightlands.com/en/brightlands-smart-services-campus"
    image: "partners/bssc.png"
  - name: "SECARTYS"
    url: "https://www.secartys.org/es/"
    image: "partners/secartys.png"
  - name: "BIA"
    url: "https://en.bia-bg.com/"
    image: "partners/bia.png"
  - name: "Digital National Coalition"
    url: "https://adn.bg/en/the-digital-national-alliance/"
    image: "partners/dna.png"
  - name: "Mentoring Europe"
    url: "https://www.mentoringeurope.eu/"
    image: "partners/mentoring_europe.svg"
  - name: "Università Telematica Internazionale UNINETTUNO"
    url: "https://www.uninettuno.it/"
    image: "partners/uninettuno.png"
